resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/3 * * * *'  



pipelines:
- name: sleep2
  steps:
  - name: First_Step
    type: Bash
    configuration:
        inputResources:
          - name: cron_trigger
    execution:
      onExecute:
        - sleep 2
        - echo "this is sleep fpr 2 seconds"
  - name: Second_Step
    type: Bash
    configuration:
      inputSteps:
        - name: First_Step
    execution:
      onExecute:
        - sleep 1000
  - name: Third_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Second_Step
    execution:
      onExecute:
        - sleep 30
  - name: Fourth_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Third_Step
    execution:
      onExecute:
        - sleep 2
