resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'  



pipelines:
- name: sleep2
  steps:
    - name: preperation_step
    type: Bash
    configuration:
        inputResources:
            - name: cron_trigger
    execution:
      onExecute:
        - sleep 1
  - name: First_Step
    type: Bash
    execution:
      onExecute:
        - sleep 120
  - name: Second_Step
    type: Bash
    configuration:
      inputSteps:
        - name: First_Step
    execution:
      onExecute:
        - sleep 120
  - name: Third_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Second_Step
    execution:
      onExecute:
        - sleep 120
  - name: Fourth_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Third_Step
    execution:
      onExecute:
        - sleep 12
- triggers:
    cron: "H 8 * * *"
