resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'  



pipelines:
- name: sleep2
  steps:
  - name: First_Step
    type: Bash
    configuration:
        inputResources:
          - name: cron_trigger
    execution:
      onExecute:
        - sleep 20
  - name: Second_Step
    type: Bash
    configuration:
      inputSteps:
        - name: First_Step
    execution:
      onExecute:
        - sleep 20
  - name: Third_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Second_Step
    execution:
      onExecute:
        - sleep 20
  - name: Fourth_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Third_Step
    execution:
      onExecute:
        - sleep 12
